// export { default as Dyn } from './Dyn.vue';
export { default as Demo1 } from './demos/Demo1.vue';
export { default as Demo2 } from './demos/Demo2.vue';
export { default as Demo3 } from './demos/Demo3.vue';
export { default as Demo4 } from './demos/Demo4.vue';
export { default as Textures } from './materials/Textures.vue';
export { default as SubSurface } from './materials/SubSurface.vue';
export { default as Matcap } from './materials/Matcap.vue';
export { default as Slider1 } from './sliders/Slider1.vue';
export { default as Slider2 } from './sliders/Slider2.vue';
